// shared/types/filters/panel/image.ts
/** The Images panel's rows, in the panel's order */
import { COMPARISON_MODIFIERS } from "../criteria.js";
import type { IMAGE_FIELDS } from "../fields.js";
import { RESOLUTION_CHOICES } from "./scene.js";
import {
  HAS_MODIFIERS,
  HAS_ONE_MODIFIERS,
  type PanelField,
  RATING_DISPLAY,
} from "./types.js";

/** Has ALL, ANY or NONE of these, or none or any at all */
const HAS_OR_PRESENCE = [...HAS_MODIFIERS, "IS_NULL", "NOT_NULL"] as const;
/** The one studio: ANY or NONE of these, or none or any at all */
const HAS_ONE_OR_PRESENCE = [
  ...HAS_ONE_MODIFIERS,
  "IS_NULL",
  "NOT_NULL",
] as const;

/** A three-state filter: "Any" sends nothing, the others send true or false */
const YES_NO_ANY = [
  { value: "true", label: "Yes", sends: true },
  { value: "false", label: "No", sends: false },
  { value: "any", label: "Any", sends: undefined },
] as const;

export const IMAGE_PANEL = [
  // Common
  {
    key: "title",
    field: "title",
    label: "Title Search",
    group: "common",
    editor: "text",
    placeholder: "Search title...",
  },
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "images",
    excludeKey: "performerIdsExclude",
  },
  {
    key: "studioIds",
    field: "studios",
    label: "Studios",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select studios...",
    modifiers: HAS_ONE_OR_PRESENCE,
    modifierKey: "studioIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "studioIdsDepth",
    hierarchyLabel: "Include sub-studios",
    countContext: "images",
    excludeKey: "studioIdsExclude",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "images",
    pinnedByDefault: true,
    excludeKey: "tagIdsExclude",
  },
  {
    key: "galleryIds",
    field: "galleries",
    label: "Galleries",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select galleries...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "galleryIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "images",
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    display: RATING_DISPLAY,
    pinnedByDefault: true,
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Images",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },
  {
    key: "oCounter",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 50 },
  },
  {
    key: "organized",
    field: "organized",
    label: "Organized",
    group: "common",
    editor: "choice",
    placeholder: "Any",
    choices: YES_NO_ANY,
    defaultValue: "any",
  },

  // Entities
  {
    key: "performerTagIds",
    field: "performer_tags",
    label: "Performer Tags",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select performer tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerTagIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "performerTagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    excludeKey: "performerTagIdsExclude",
  },

  // Dates
  {
    key: "date",
    field: "date",
    label: "Image Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },

  // Other
  {
    key: "resolution",
    field: "resolution",
    label: "Resolution",
    group: "other",
    editor: "enum",
    placeholder: "Any resolution",
    choices: RESOLUTION_CHOICES,
    modifiers: COMPARISON_MODIFIERS,
    modifierKey: "resolutionModifier",
    defaultModifier: "EQUALS",
  },
  {
    key: "orientation",
    field: "orientation",
    label: "Orientation",
    group: "other",
    editor: "enum",
    multi: true,
    placeholder: "Any orientation",
    choices: [
      { value: "LANDSCAPE", label: "Landscape" },
      { value: "PORTRAIT", label: "Portrait" },
      { value: "SQUARE", label: "Square" },
    ],
  },
  {
    key: "details",
    field: "details",
    label: "Details Search",
    group: "other",
    editor: "text",
    placeholder: "Search details...",
  },
  {
    key: "code",
    field: "code",
    label: "Code",
    group: "other",
    editor: "text",
    placeholder: "Search code...",
  },
  {
    key: "photographer",
    field: "photographer",
    label: "Photographer",
    group: "other",
    editor: "text",
    placeholder: "Search photographer...",
  },
  {
    key: "path",
    field: "path",
    label: "Path",
    group: "other",
    editor: "text",
    placeholder: "Search path...",
    modifierKey: "pathModifier",
    modifiers: ["INCLUDES", "EXCLUDES", "EQUALS", "NOT_EQUALS", "STARTS_WITH"],
  },
  {
    key: "url",
    field: "url",
    label: "URL",
    group: "other",
    editor: "text",
    placeholder: "Search URLs...",
  },
  {
    key: "performerFavorite",
    field: "performer_favorite",
    label: "Favorite Performers",
    group: "other",
    editor: "choice",
    placeholder: "Any",
    choices: YES_NO_ANY,
    defaultValue: "any",
  },
  {
    key: "studioFavorite",
    field: "studio_favorite",
    label: "Favorite Studios",
    group: "other",
    editor: "choice",
    placeholder: "Any",
    choices: YES_NO_ANY,
    defaultValue: "any",
  },
  {
    key: "tagFavorite",
    field: "tag_favorite",
    label: "Favorite Tags",
    group: "other",
    editor: "choice",
    placeholder: "Any",
    choices: YES_NO_ANY,
    defaultValue: "any",
  },
  {
    key: "performerCount",
    field: "performer_count",
    label: "Performer Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 20 },
  },
  {
    key: "performerAge",
    field: "performer_age",
    label: "Performer Age",
    group: "other",
    editor: "number",
    bounds: { min: 18, max: 100 },
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof IMAGE_FIELDS, string>
>[];
