// shared/types/filters/panel/performer.ts
/** The Performers panel's rows, in the panel's order */
import type { PERFORMER_FIELDS } from "../fields.js";
import { HAS_MODIFIERS, type PanelField, RATING_DISPLAY } from "./types.js";

/** Has ALL, ANY or NONE of these, or has none or any at all */
const HAS_OR_PRESENCE = [...HAS_MODIFIERS, "IS_NULL", "NOT_NULL"] as const;

/** A text box's condition select: contains or not, or has none or any */
const TEXT_OR_PRESENCE = [
  "INCLUDES",
  "EXCLUDES",
  "IS_NULL",
  "NOT_NULL",
] as const;

/** A box group's condition select (Gender): any or none of the boxes, or has none or any */
const ANY_NONE_OR_PRESENCE = [
  "INCLUDES",
  "EXCLUDES",
  "IS_NULL",
  "NOT_NULL",
] as const;

/** Yes, No or Any: Any sends nothing */
const YES_NO_ANY = [
  { value: "any", label: "Any", sends: undefined },
  { value: "true", label: "Yes", sends: true },
  { value: "false", label: "No", sends: false },
] as const;

export const PERFORMER_PANEL = [
  // Common
  {
    key: "name",
    field: "name",
    label: "Name Search",
    group: "common",
    editor: "text",
    placeholder: "Search name...",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "performers",
    pinnedByDefault: true,
    excludeKey: "tagIdsExclude",
  },
  {
    key: "tagFavorite",
    field: "tag_favorite",
    label: "Has a Favorite Tag",
    group: "common",
    editor: "choice",
    choices: YES_NO_ANY,
    defaultValue: "any",
  },
  {
    key: "gender",
    field: "gender",
    label: "Gender",
    group: "common",
    editor: "enum",
    // A box for each gender; a preset saved while it took one value (the
    // owner's default `gender: "FEMALE"`) reads as a one-element list
    multi: true,
    modifiers: ANY_NONE_OR_PRESENCE,
    modifierKey: "genderModifier",
    defaultModifier: "INCLUDES",
    placeholder: "Any gender",
    choices: [
      { value: "MALE", label: "Male" },
      { value: "FEMALE", label: "Female" },
      { value: "TRANSGENDER_MALE", label: "Trans Male" },
      { value: "TRANSGENDER_FEMALE", label: "Trans Female" },
      { value: "INTERSEX", label: "Intersex" },
      { value: "NON_BINARY", label: "Non-Binary" },
    ],
    pinnedByDefault: true,
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    display: RATING_DISPLAY,
    pinnedByDefault: true,
  },
  {
    key: "oCounter",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "sceneCount",
    field: "scene_count",
    label: "Scene Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Performers",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },

  // Entities: the performers' scenes
  {
    key: "studioIds",
    field: "studios",
    label: "Studios",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select studios...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "studioIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "studioIdsDepth",
    hierarchyLabel: "Include sub-studios",
    excludeKey: "studioIdsExclude",
  },
  {
    key: "groupIds",
    field: "groups",
    label: "Collections",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select collections...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "groupIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "in",
  },
  {
    // Shares a scene the viewer can see with these performers
    key: "performerIds",
    field: "performers",
    label: "Appears With",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    excludeKey: "performerIdsExclude",
  },

  // Dates
  {
    key: "age",
    field: "age",
    label: "Age",
    group: "dates",
    editor: "number",
    bounds: { min: 18, max: 100 },
  },
  {
    key: "birthYear",
    field: "birth_year",
    label: "Birth Year",
    group: "dates",
    editor: "number",
    bounds: { min: 1900, max: 2010 },
  },
  {
    key: "deathYear",
    field: "death_year",
    label: "Death Year",
    group: "dates",
    editor: "number",
    bounds: { min: 1900, max: 2100 },
  },
  {
    key: "careerLength",
    field: "career_length",
    label: "Career Length (years)",
    group: "dates",
    editor: "number",
    modifierKey: "careerLengthModifier",
    bounds: { min: 0, max: 50 },
    unit: "years",
  },
  {
    key: "birthdate",
    field: "birthdate",
    label: "Birth Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "deathDate",
    field: "death_date",
    label: "Death Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },

  // Attributes: hair, eyes, ethnicity and breast type are Stash free text,
  // offered as a select of the usual values
  {
    key: "hairColor",
    field: "hair_color",
    label: "Hair Color",
    group: "attributes",
    editor: "enum",
    placeholder: "Any hair color",
    choices: [
      { value: "BLONDE", label: "Blonde" },
      { value: "BRUNETTE", label: "Brunette" },
      { value: "BLACK", label: "Black" },
      { value: "RED", label: "Red" },
      { value: "AUBURN", label: "Auburn" },
      { value: "GREY", label: "Grey" },
      { value: "BALD", label: "Bald" },
      { value: "VARIOUS", label: "Various" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "eyeColor",
    field: "eye_color",
    label: "Eye Color",
    group: "attributes",
    editor: "enum",
    placeholder: "Any eye color",
    choices: [
      { value: "BROWN", label: "Brown" },
      { value: "BLUE", label: "Blue" },
      { value: "GREEN", label: "Green" },
      { value: "GREY", label: "Grey" },
      { value: "HAZEL", label: "Hazel" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "ethnicity",
    field: "ethnicity",
    label: "Ethnicity",
    group: "attributes",
    editor: "enum",
    placeholder: "Any ethnicity",
    choices: [
      { value: "CAUCASIAN", label: "Caucasian" },
      { value: "BLACK", label: "Black" },
      { value: "ASIAN", label: "Asian" },
      { value: "INDIAN", label: "Indian" },
      { value: "LATIN", label: "Latin" },
      { value: "MIDDLE_EASTERN", label: "Middle Eastern" },
      { value: "MIXED", label: "Mixed" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "fakeTits",
    field: "fake_tits",
    label: "Breast Type",
    group: "attributes",
    editor: "enum",
    placeholder: "Any",
    choices: [
      { value: "Fake", label: "Fake/Augmented" },
      { value: "Natural", label: "Natural" },
    ],
  },
  {
    key: "country",
    field: "country",
    label: "Country",
    group: "attributes",
    editor: "text",
    placeholder: "e.g. US",
  },
  {
    key: "circumcised",
    field: "circumcised",
    label: "Circumcised",
    group: "attributes",
    editor: "enum",
    placeholder: "Any",
    choices: [
      { value: "CUT", label: "Cut" },
      { value: "UNCUT", label: "Uncut" },
    ],
  },
  {
    key: "measurements",
    field: "measurements",
    label: "Measurements",
    group: "attributes",
    editor: "text",
    placeholder: "e.g. 34-24-34",
  },
  {
    key: "tattoos",
    field: "tattoos",
    label: "Tattoos",
    group: "attributes",
    editor: "text",
    placeholder: "Search tattoos...",
  },
  {
    key: "piercings",
    field: "piercings",
    label: "Piercings",
    group: "attributes",
    editor: "text",
    placeholder: "Search piercings...",
  },
  {
    key: "height",
    field: "height",
    label: "Height (cm)",
    group: "attributes",
    editor: "number",
    modifierKey: "heightModifier",
    bounds: { min: 100, max: 250 },
    measure: "height",
  },
  {
    key: "weight",
    field: "weight",
    label: "Weight (kg)",
    group: "attributes",
    editor: "number",
    modifierKey: "weightModifier",
    bounds: { min: 30, max: 200 },
    measure: "weight",
  },
  {
    key: "penisLength",
    field: "penis_length",
    label: "Penis Length (cm)",
    group: "attributes",
    editor: "number",
    modifierKey: "penisLengthModifier",
    bounds: { min: 0, max: 40 },
    measure: "length",
  },

  // Other
  {
    key: "playCount",
    field: "play_count",
    label: "Play Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "imageCount",
    field: "image_count",
    label: "Image Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 10000 },
  },
  {
    key: "galleryCount",
    field: "gallery_count",
    label: "Gallery Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "markerCount",
    field: "marker_count",
    label: "Marker Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "disambiguation",
    field: "disambiguation",
    label: "Disambiguation",
    group: "other",
    editor: "text",
    placeholder: "Search disambiguation...",
  },
  {
    key: "aliases",
    field: "aliases",
    label: "Aliases",
    group: "other",
    editor: "text",
    placeholder: "Search aliases...",
    modifierKey: "aliasesModifier",
    modifiers: TEXT_OR_PRESENCE,
  },
  {
    key: "url",
    field: "url",
    label: "URL",
    group: "other",
    editor: "text",
    placeholder: "Search URLs...",
    modifierKey: "urlModifier",
    modifiers: TEXT_OR_PRESENCE,
  },
  {
    key: "stashId",
    field: "stash_id",
    label: "StashDB ID",
    group: "other",
    editor: "text",
    placeholder: "Search StashDB ID...",
    modifierKey: "stashIdModifier",
    modifiers: ["EQUALS", "IS_NULL", "NOT_NULL"],
  },
  {
    key: "details",
    field: "details",
    label: "Details Search",
    group: "other",
    editor: "text",
    placeholder: "Search details...",
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof PERFORMER_FIELDS, string>
>[];
