// shared/types/filters/panel/scene.ts
/** The Scenes panel's rows, in the panel's order */
import { COMPARISON_MODIFIERS } from "../criteria.js";
import type { SCENE_FIELDS } from "../fields.js";
import {
  HAS_MODIFIERS,
  HAS_ONE_MODIFIERS,
  type PanelField,
  type SendingChoice,
} from "./types.js";

/** Stash's resolutions as its panel offers them: VR_HD left out */
export const RESOLUTION_CHOICES = [
  { value: "VERY_LOW", label: "144p" },
  { value: "LOW", label: "240p" },
  { value: "R360P", label: "360p" },
  { value: "STANDARD", label: "480p" },
  { value: "WEB_HD", label: "540p" },
  { value: "STANDARD_HD", label: "720p" },
  { value: "FULL_HD", label: "1080p" },
  { value: "QUAD_HD", label: "1440p" },
  { value: "FOUR_K", label: "4K" },
  { value: "FIVE_K", label: "5K" },
  { value: "SIX_K", label: "6K" },
  { value: "SEVEN_K", label: "7K" },
  { value: "EIGHT_K", label: "8K" },
  { value: "HUGE", label: "Huge" },
] as const;

/** Caption languages as Stash's editor sets them (its "unknown" is `00`) */
const CAPTION_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "de", label: "German" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "nl", label: "Dutch" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "ru", label: "Russian" },
  { value: "sv", label: "Swedish" },
  { value: "tr", label: "Turkish" },
  { value: "zh", label: "Chinese" },
  { value: "00", label: "Unknown" },
] as const;

/**
 * Yes, No and Any: Yes sends `true`, No sends `false`, Any sends nothing.
 * The state holds the choice's text and the URL its boolean, so a link or a
 * preset saved with `favorite=true` reads as Yes.
 */
const THREE_STATE = [
  { value: "true", label: "Yes", sends: true },
  { value: "false", label: "No", sends: false },
  { value: "any", label: "Any", sends: undefined },
] as const satisfies readonly SendingChoice[];

/** Has ANY or NONE of these, or has none or any at all (a scene's one studio) */
const HAS_ONE_OR_PRESENCE = [
  ...HAS_ONE_MODIFIERS,
  "IS_NULL",
  "NOT_NULL",
] as const;

/** Has ALL, ANY or NONE of these, or has none or any at all */
const HAS_OR_PRESENCE = [...HAS_MODIFIERS, "IS_NULL", "NOT_NULL"] as const;

export const SCENE_PANEL = [
  // Common
  {
    key: "title",
    field: "title",
    label: "Title Search",
    group: "common",
    editor: "text",
    placeholder: "Search title...",
  },
  {
    key: "details",
    field: "details",
    label: "Details Search",
    group: "common",
    editor: "text",
    placeholder: "Search details...",
  },
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "scenes",
    pinnedByDefault: true,
    excludeKey: "performerIdsExclude",
  },
  {
    key: "studioId",
    field: "studios",
    label: "Studios",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select studios...",
    modifiers: HAS_ONE_OR_PRESENCE,
    modifierKey: "studioIdModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "studioIdDepth",
    hierarchyLabel: "Include sub-studios",
    countContext: "scenes",
    excludeKey: "studioIdExclude",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "scenes",
    pinnedByDefault: true,
    excludeKey: "tagIdsExclude",
  },
  {
    key: "performerTagIds",
    field: "performer_tags",
    label: "Performer Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performer tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerTagIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "performerTagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    excludeKey: "performerTagIdsExclude",
  },
  {
    key: "groupIds",
    field: "groups",
    label: "Collections",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select collections...",
    modifiers: HAS_ONE_OR_PRESENCE,
    modifierKey: "groupIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "in",
    hierarchyKey: "groupIdsDepth",
    hierarchyLabel: "Include sub-collections",
    countContext: "scenes",
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "oCount",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 300 },
  },
  {
    key: "duration",
    field: "duration",
    label: "Duration (minutes)",
    group: "common",
    editor: "number",
    bounds: { min: 1, max: 300 },
    scale: 60,
    unit: "minutes",
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Scenes",
    group: "common",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "performerFavorite",
    field: "performer_favorite",
    label: "Favorite Performers",
    group: "common",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "studioFavorite",
    field: "studio_favorite",
    label: "Favorite Studios",
    group: "common",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "tagFavorite",
    field: "tag_favorite",
    label: "Favorite Tags",
    group: "common",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },

  // Entities
  {
    key: "galleryIds",
    field: "galleries",
    label: "Galleries",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select galleries...",
    modifiers: HAS_OR_PRESENCE,
    modifierKey: "galleryIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
  },
  {
    key: "playlistIds",
    field: "playlists",
    label: "Playlists",
    group: "entities",
    editor: "ref",
    source: "playlists",
    multi: true,
    placeholder: "Select playlists...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "playlistIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
  },
  {
    key: "inAnyPlaylist",
    field: "in_any_playlist",
    label: "In any of my playlists",
    group: "entities",
    editor: "choice",
    choices: [
      { value: "true", label: "In one of your own playlists", sends: true },
      { value: "false", label: "In none of your own playlists", sends: false },
      { value: "any", label: "Any", sends: undefined },
    ],
    defaultValue: "any",
  },

  // Dates
  {
    key: "date",
    field: "date",
    label: "Scene Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "lastPlayedAt",
    field: "last_played_at",
    label: "Last Played Date",
    group: "dates",
    editor: "date",
  },

  // Video
  {
    key: "resolution",
    field: "resolution",
    label: "Resolution",
    group: "video",
    editor: "enum",
    placeholder: "Any resolution",
    choices: RESOLUTION_CHOICES,
    modifiers: COMPARISON_MODIFIERS,
    modifierKey: "resolutionModifier",
    defaultModifier: "EQUALS",
  },
  {
    key: "bitrate",
    field: "bitrate",
    label: "Bitrate (Mbps)",
    group: "video",
    editor: "number",
    bounds: { min: 0, max: 100 },
    scale: 1_000_000,
    unit: "Mbps",
  },
  {
    key: "framerate",
    field: "framerate",
    label: "Framerate (fps)",
    group: "video",
    editor: "number",
    bounds: { min: 0, max: 120 },
    unit: "fps",
  },
  {
    key: "orientation",
    field: "orientation",
    label: "Orientation",
    group: "video",
    editor: "enum",
    multi: true,
    placeholder: "Any orientation",
    choices: [
      { value: "LANDSCAPE", label: "Landscape" },
      { value: "PORTRAIT", label: "Portrait" },
      { value: "SQUARE", label: "Square" },
    ],
  },
  {
    key: "videoCodec",
    field: "video_codec",
    label: "Video Codec",
    group: "video",
    editor: "text",
    placeholder: "e.g. h264, hevc",
  },
  {
    key: "audioCodec",
    field: "audio_codec",
    label: "Audio Codec",
    group: "video",
    editor: "text",
    placeholder: "e.g. aac, mp3",
  },

  // Other
  {
    key: "director",
    field: "director",
    label: "Director Search",
    group: "other",
    editor: "text",
    placeholder: "Search director...",
  },
  {
    key: "path",
    field: "path",
    label: "Path",
    group: "other",
    editor: "text",
    placeholder: "Search path...",
    modifierKey: "pathModifier",
    modifiers: ["INCLUDES", "EXCLUDES", "EQUALS", "STARTS_WITH"],
  },
  {
    key: "url",
    field: "url",
    label: "URL",
    group: "other",
    editor: "text",
    placeholder: "Search URLs...",
  },
  {
    key: "code",
    field: "code",
    label: "Code",
    group: "other",
    editor: "text",
    placeholder: "Search code...",
  },
  {
    key: "captions",
    field: "captions",
    label: "Captions",
    group: "other",
    editor: "enum",
    placeholder: "Any language",
    choices: CAPTION_LANGUAGES,
    modifiers: ["EQUALS", "NOT_EQUALS", "IS_NULL", "NOT_NULL"],
    modifierKey: "captionsModifier",
    defaultModifier: "EQUALS",
  },
  {
    key: "organized",
    field: "organized",
    label: "Organized",
    group: "other",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "hasMarkers",
    field: "has_markers",
    label: "Has Markers",
    group: "other",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "duplicated",
    field: "duplicated",
    label: "Duplicated",
    group: "other",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "watched",
    field: "watched",
    label: "Watched",
    group: "other",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "inProgress",
    field: "in_progress",
    label: "In Progress",
    group: "other",
    editor: "choice",
    choices: THREE_STATE,
    defaultValue: "any",
  },
  {
    key: "playDuration",
    field: "play_duration",
    label: "Play Duration (minutes)",
    group: "other",
    editor: "number",
    bounds: { min: 1, max: 300 },
    scale: 60,
    unit: "minutes",
  },
  {
    key: "playCount",
    field: "play_count",
    label: "Play Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "performerCount",
    field: "performer_count",
    label: "Performer Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 20 },
  },
  {
    key: "performerAge",
    field: "performer_age",
    label: "Performer Age",
    group: "other",
    editor: "number",
    bounds: { min: 18, max: 100 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 50 },
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof SCENE_FIELDS, string>
>[];
