// shared/types/filters/panel/tag.ts
/** The Tags panel's rows, in the panel's order */
import type { TAG_FIELDS } from "../fields.js";
import { HAS_MODIFIERS, INCLUDES_ONLY, type PanelField } from "./types.js";

/** A text box's condition select: contains or not, or has none or any */
const TEXT_OR_PRESENCE = [
  "INCLUDES",
  "EXCLUDES",
  "IS_NULL",
  "NOT_NULL",
] as const;

export const TAG_PANEL = [
  // Common
  {
    key: "name",
    field: "name",
    label: "Name Search",
    group: "common",
    editor: "text",
    placeholder: "Search name...",
  },
  {
    key: "description",
    field: "description",
    label: "Description Search",
    group: "common",
    editor: "text",
    placeholder: "Search description...",
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "sceneCount",
    field: "scene_count",
    label: "Scene Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "oCounter",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "playCount",
    field: "play_count",
    label: "Play Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Tags",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },

  // Entities
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: INCLUDES_ONLY,
    excludeKey: "performerIdsExclude",
  },
  {
    key: "studioId",
    field: "studios",
    label: "Studio",
    group: "entities",
    editor: "ref",
    multi: false,
    placeholder: "Select studio...",
    modifiers: INCLUDES_ONLY,
  },
  {
    key: "groupIds",
    field: "groups",
    label: "Collections",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select collections...",
    modifiers: INCLUDES_ONLY,
  },
  {
    // The tags directly under these, or at any depth
    key: "parentIds",
    field: "parents",
    label: "Parent Tags",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "parentIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "parentIdsDepth",
    hierarchyLabel: "Include sub-tags",
  },
  {
    // The tags directly above these, or at any height
    key: "childIds",
    field: "children",
    label: "Child Tags",
    group: "entities",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "childIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "childIdsDepth",
    hierarchyLabel: "Include all parent tags",
  },

  // Dates
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },

  // Other
  {
    key: "parentCount",
    field: "parent_count",
    label: "Parent Tag Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 100 },
  },
  {
    key: "childCount",
    field: "child_count",
    label: "Child Tag Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "imageCount",
    field: "image_count",
    label: "Image Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 10000 },
  },
  {
    key: "galleryCount",
    field: "gallery_count",
    label: "Gallery Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "performerCount",
    field: "performer_count",
    label: "Performer Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "studioCount",
    field: "studio_count",
    label: "Studio Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "groupCount",
    field: "group_count",
    label: "Collection Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "markerCount",
    field: "marker_count",
    label: "Marker Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 10000 },
  },
  {
    key: "aliases",
    field: "aliases",
    label: "Aliases",
    group: "other",
    editor: "text",
    placeholder: "Search aliases...",
    modifierKey: "aliasesModifier",
    modifiers: TEXT_OR_PRESENCE,
  },
  {
    key: "stashId",
    field: "stash_id",
    label: "StashDB ID",
    group: "other",
    editor: "text",
    placeholder: "Search StashDB ID...",
    modifierKey: "stashIdModifier",
    modifiers: ["EQUALS", "IS_NULL", "NOT_NULL"],
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof TAG_FIELDS, string>
>[];
