// shared/types/filters/index.ts
/**
 * The list filter and sort contract (item 38): every list's filter fields,
 * sorts and filter-panel keys, declared once. The client's filter options and
 * the server's request parser both read it; a new filter starts here.
 */
export {
  BREAST_TYPES,
  CIRCUMCISED,
  COMPARISON_MODIFIERS,
  DATE_MODIFIERS,
  ENTITY_KINDS,
  ENUM_MODIFIERS,
  ETHNICITIES,
  EYE_COLORS,
  FIELD_KINDS,
  GENDERS,
  HAIR_COLORS,
  MAX_PLAYLIST_VALUES,
  NUMBER_MODIFIERS,
  ORIENTATIONS,
  PATH_MODIFIERS,
  PRESENCE_MODIFIERS,
  RANGE_MODIFIERS,
  REF_MODIFIERS,
  REF_PRESENCE_MODIFIERS,
  RESOLUTIONS,
  SINGLE_REF_MODIFIERS,
  SINGLE_REF_PRESENCE_MODIFIERS,
  TEXT_MAX_LENGTH,
  TEXT_MODIFIERS,
} from "./criteria.js";
export type {
  BooleanSpec,
  DateModifier,
  DateSpec,
  EntityKind,
  EnumModifier,
  EnumSpec,
  FieldKind,
  FieldSpec,
  InstanceSpec,
  NumberModifier,
  NumberSpec,
  PlaylistSpec,
  PresenceModifier,
  RangeModifier,
  RefFieldModifier,
  RefModifier,
  RefSpec,
  Resolution,
  TextModifier,
  TextSpec,
} from "./criteria.js";

export {
  CLIP_FIELDS,
  DEFAULT_PLAYLIST_ITEM_SORT,
  DEFAULT_RECOMMENDED_SORT,
  DEFAULT_SORT,
  FIELDS,
  FILTER_BODY_KEYS,
  GALLERY_FIELDS,
  GROUP_FIELDS,
  IMAGE_FIELDS,
  LIST_FIELDS,
  LIST_KINDS,
  MAX_REF_VALUES,
  MINIMAL_IDS_MAX,
  MINIMAL_PER_PAGE_MAX,
  PERFORMER_FIELDS,
  PER_PAGE_MAX,
  PLAYLIST_ITEM_SORTS,
  Q_MAX_LENGTH,
  RECOMMENDED_LIMIT,
  RECOMMENDED_SORTS,
  SCENE_FIELDS,
  SORTS,
  SORT_DIRECTIONS,
  STUDIO_FIELDS,
  TAG_FIELDS,
} from "./fields.js";
export type {
  FieldSpecOf,
  FilterBodyKey,
  ListKind,
  PlaylistItemSort,
  RandomSortKey,
  RecommendedSort,
  SortDirection,
  SortOf,
} from "./fields.js";

export {
  CLIP_UI_KEYS,
  GALLERY_UI_KEYS,
  GROUP_UI_KEYS,
  IMAGE_UI_KEYS,
  PERFORMER_UI_KEYS,
  SCENE_UI_KEYS,
  STUDIO_UI_KEYS,
  TAG_UI_KEYS,
  UI_KEYS,
} from "./uiKeys.js";
export type { UiKey } from "./uiKeys.js";

export {
  CLIP_PANEL,
  EDITOR_KINDS,
  GALLERY_PANEL,
  GROUP_PANEL,
  HAS_MODIFIERS,
  HAS_ONE_MODIFIERS,
  IMAGE_PANEL,
  INCLUDES_ONLY,
  PANEL_FIELDS,
  PANEL_GROUPS,
  PANEL_GROUP_LABELS,
  PERFORMER_PANEL,
  SCENE_PANEL,
  STUDIO_PANEL,
  TAG_PANEL,
} from "./panel/index.js";
export type {
  Choice,
  ChoiceField,
  CountContext,
  DateField,
  EditorKind,
  EnumField,
  NumberField,
  PanelField,
  PanelGroup,
  RefField,
  SendingChoice,
  TextField,
  ToggleField,
} from "./panel/index.js";

export type {
  ClipFilterInput,
  ClipListRequestInput,
  CriterionInput,
  DateInput,
  EnumInput,
  FilterInput,
  GalleryFilterInput,
  GroupFilterInput,
  HierarchicalRefInput,
  ImageFilterInput,
  ListPageInput,
  ListRequestInput,
  MultiEnumInput,
  NumberInput,
  PerformerFilterInput,
  PlaylistInput,
  RefInput,
  SceneFilterInput,
  StudioFilterInput,
  TagFilterInput,
  TextInput,
} from "./wire.js";

export {
  MATCHES,
  ROOT_MATCH_KEY,
  WHERE_LIMITS,
  anyMergeCap,
  anyMergeKey,
  groupKeyOf,
  isWhereGroup,
  parseRowKey,
  rowKeyOf,
} from "./tree.js";
export type {
  Match,
  RowKey,
  WhereField,
  WhereGroup,
  WhereLeaf,
  WhereNode,
} from "./tree.js";

export { DEFAULT_PINNED_FILTERS, PIN_LIMIT, defaultPinsOf } from "./pins.js";
export type { FilterPins, ListPins, PinnedFilter } from "./pins.js";
