// Re-exporting stub — canonical definitions live in shared/types/api/download.ts
export type {
  SerializedDownload,
  StartEntityDownloadRequest,
  StartSceneDownloadParams,
  StartSceneDownloadResponse,
  StartImageDownloadParams,
  StartImageDownloadResponse,
  StartPlaylistDownloadParams,
  StartPlaylistDownloadResponse,
  PlaylistTooLargeResponse,
  GetUserDownloadsResponse,
  GetDownloadStatusParams,
  GetDownloadStatusResponse,
  GetDownloadFileParams,
  DeleteDownloadParams,
  DeleteDownloadResponse,
  RetryDownloadParams,
  RetryDownloadResponse,
} from "@peek/shared-types/api/download.js";
