// Generated by npm run fixtures:generate; do not edit

export const FIXTURE_API_KEY = "stash-replay-key";

export const FIXTURE_ID_OFFSET = 100000;

export const FIXTURE_LIBRARY = {
  scenes: 36,
  performers: 11,
  studios: 10,
  tags: 11,
  groups: 3,
  galleries: 2,
  images: 9,
  clips: 2,
};

export const TEST_ENTITIES = {
  sceneWithRelations: "100003",
  performerWithScenes: "100006",
  studioWithScenes: "100005",
  tagWithEntities: "100003",
  groupWithScenes: "100001",
  sceneInGroup: "100001",
  galleryWithImages: "100001",
  galleryWithScenes: "100001",
  restrictableTag: "100001",
  galleryPerformerForInheritance: "100006",
  imageWithGalleryInheritance: "100004",
  imageWithOwnProperties: "100005",
  sceneWithInheritedTags: "100002",
  inheritedTagFromPerformerOrStudio: "",
};
