import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import globals from "globals";
import tseslint from "typescript-eslint";

const testFiles = ["tests/**/*.ts", "integration/**/*.ts"];

// no-restricted-syntax takes one option list per config block, and a later
// block that sets the rule for some files replaces the whole list there. So
// every selector lives in RESTRICTED: the source block uses all of it, and a
// block for some files passes restrictedExcept(...) or [...RESTRICTED, X],
// so no selector drops out by accident.

// The writer rule: every transaction is a dbWrite unit, so writers queue in
// Node instead of starving each other inside the engine
const WRITER_RULE = {
  selector: 'MemberExpression[property.name="$transaction"]',
  message: "use dbWriteTransaction / dbWriteBatch (server-sql.md, Writes)",
};

// In-memory keys carry the instance, spelled one way: a template or string
// holding the key separator (\0) is a key built by hand
const ENTITY_KEY_RULE = {
  selector: "TemplateElement[value.cooked=/\\u0000/], Literal[value=/\\u0000/]",
  message:
    "build in-memory keys with entityKey/compositeKey (utils/entityRef.ts)",
};

// Error text stays in the log: a body built from a caught error's `message`
// leaks database messages, file paths and queries. Handlers throw typed
// errors (middleware/errorHandler.ts) and the central handler answers.
const ERROR_TEXT_RULE = {
  selector:
    'CallExpression[callee.property.name=/^(json|send)$/] MemberExpression[property.name="message"]',
  message:
    "do not put error text in a response; throw an AppError (middleware/errorHandler.ts)",
};

const RESTRICTED = [WRITER_RULE, ENTITY_KEY_RULE, ERROR_TEXT_RULE];

// Handlers and services name their dependencies at the top: an import inside
// a function hides one from the reader and adds a module lookup to every call
// (vi.mock is hoisted, so tests mock a top-level import the same way)
const DYNAMIC_IMPORT_RULE = {
  selector: "ImportExpression",
  message: "use a top-level import",
};

/** The rule's options with every selector but the ones named. */
const restrictedExcept = (...dropped) => [
  "error",
  ...RESTRICTED.filter((selector) => !dropped.includes(selector)),
];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "prisma/migrations/**",
      // Auto-generated by GraphQL codegen
      "graphql/generated/**",
      // Non-TypeScript scripts (not covered by tsconfig)
      "**/*.mjs",
      "**/*.js",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    files: ["**/*.ts"],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.node,
        NodeJS: "readonly",
      },
    },
    rules: {
      // --- Core rules from issue #465 (all error) ---
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",

      // A default does not excuse a missing union member, so a new entity
      // type cannot fall silently into it
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      // Raw SQL rows are typed as SQLite returns them (a COUNT or SUM is a
      // bigint, a BOOLEAN column a boolean), so a flagged Number() is dropped
      // only when the value's type is honest
      "@typescript-eslint/no-unnecessary-type-conversion": "error",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",

      // Ratcheted in eslint-suppressions.json, fixed by the PRs that own the
      // code: a `||` on a string or number (where "" or 0 can mean something,
      // such as "every instance"), and conditions that only become checkable
      // once rows are honestly typed. The counts may only fall.
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",

      // Not adopted. Prisma enums are string-literal unions, so TypeScript
      // already rejects a comparison with a non-member; the other is style.
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",

      // The writer, entity key and error text rules (RESTRICTED, above)
      "no-restricted-syntax": ["error", ...RESTRICTED],
    },
  },
  // No dynamic imports in handlers and services (DYNAMIC_IMPORT_RULE)
  {
    files: ["controllers/**/*.ts", "routes/**/*.ts", "services/**/*.ts"],
    rules: {
      "no-restricted-syntax": ["error", ...RESTRICTED, DYNAMIC_IMPORT_RULE],
    },
  },
  // Handlers read the request's instances; they never look them up
  {
    files: ["controllers/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/services/UserInstanceService.js"],
              importNames: ["getUserAllowedInstanceIds"],
              message:
                "read req.allowedInstanceIds (set by requireCacheReady, requirePickerReady or withAllowedInstances)",
            },
          ],
        },
      ],
    },
  },
  // The one place that calls $transaction
  {
    files: ["utils/dbWrite.ts"],
    rules: {
      "no-restricted-syntax": restrictedExcept(WRITER_RULE),
    },
  },
  // The one place that builds keys with the separator
  {
    files: ["utils/entityRef.ts"],
    rules: {
      "no-restricted-syntax": restrictedExcept(ENTITY_KEY_RULE),
    },
  },
  // The central handler answers with the text of an AppError
  {
    files: ["middleware/errorHandler.ts"],
    rules: {
      "no-restricted-syntax": restrictedExcept(ERROR_TEXT_RULE),
    },
  },
  // Tests mock $transaction and spell keys out in their expectations
  {
    files: testFiles,
    rules: {
      "no-restricted-syntax": "off",
    },
  },
  // Tests: the source rules above, plus vitest's. tsconfig.json excludes
  // tests/ and integration/, so they are typed by tsconfig.tests.json.
  {
    files: testFiles,
    ...vitest.configs.recommended,
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: ["./tsconfig.tests.json"],
      },
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // vitest's version allows `expect(mock.method)`
      "@typescript-eslint/unbound-method": "off",
      "vitest/unbound-method": "error",
      // expect(value, "message")
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // Helpers named expect* assert too
      "vitest/expect-expect": [
        "error",
        { assertFunctionNames: ["expect", "expect*"] },
      ],
      "vitest/no-standalone-expect": [
        "error",
        {
          additionalTestBlockFunctions: [
            "beforeAll",
            "beforeEach",
            "afterEach",
            "afterAll",
          ],
        },
      ],
    },
  },
  // untrusted() and malformedRow() are the deliberate casts for invalid input:
  // their type parameter is the target type, used once by design.
  {
    files: ["tests/helpers/untrusted.ts"],
    rules: {
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
    },
  }
);
