import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "prisma/migrations/**",
      // Unit test directories and files
      "tests/**",
      "**/*.test.ts",
      "**/__tests__/**",
      // Integration test directory (has its own tsconfig excluded from main build)
      "integration/**",
      // Auto-generated by GraphQL codegen
      "graphql/generated/**",
      // Non-TypeScript scripts (not covered by tsconfig)
      "**/*.mjs",
      "**/*.js",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    files: ["**/*.ts"],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.node,
        NodeJS: "readonly",
      },
    },
    rules: {
      // --- Core rules from issue #465 (all error) ---
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",

      // --- Strict rules deferred to follow-up PRs ---
      // These are valid improvements but out of scope for #465.
      // no-unnecessary-condition: ~414 violations, mostly redundant null checks
      "@typescript-eslint/no-unnecessary-condition": "off",
      // no-unsafe-enum-comparison: ~218 violations, Prisma enum patterns
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      // Cosmetic/style rules — enable incrementally later
      "@typescript-eslint/no-unnecessary-type-conversion": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
    },
  },
);
