/**
 * npm run fixtures:generate turns the recorded shape into the replay
 * library and its manifest (sweep item 83), offline and deterministically.
 * These tests write into a temporary directory, never into fixture/.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import path from "path";
import { pathToFileURL } from "url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generate, main } from "../../../integration/stash-replay/generate.js";
import {
  ENTITY_TYPES,
  isRecord,
  parseReplayLibrary,
} from "../../../integration/stash-replay/library.js";
import type { RecordedShape } from "../../../integration/stash-replay/synth.js";
import { must } from "../../helpers/must.js";
import { OWNER_TEST_ENTITIES, testStashShape } from "./shapeFixture.js";

let dir = "";

beforeEach(() => {
  dir = mkdtempSync(path.join(tmpdir(), "stash-replay-generate-"));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

function writeShape(shape: RecordedShape): string {
  const shapePath = path.join(dir, "shape.json");
  writeFileSync(shapePath, JSON.stringify(shape));
  return shapePath;
}

/** A shape of two scenes and one performer, with nothing else. */
function tinyShape(): RecordedShape {
  const shape = testStashShape();
  shape.entities.scene = shape.entities.scene.slice(0, 2);
  for (const scene of shape.entities.scene) {
    scene.relations = { performers: [{ id: "100006" }] };
  }
  shape.entities.performer = shape.entities.performer
    .filter((performer) => performer.id === "100006")
    .map((performer) => ({ ...performer, relations: {} }));
  shape.entities.studio = [];
  shape.entities.tag = [];
  shape.entities.group = [];
  shape.entities.gallery = [];
  shape.entities.image = [];
  return shape;
}

describe("generate", () => {
  it("fails listing unmet minimums when the shape is too small to extend", () => {
    const shapePath = writeShape(tinyShape());
    const outDir = path.join(dir, "out");

    let message = "";
    try {
      generate({ shapePath, outDir, check: false });
    } catch (error) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toContain("the library misses E2E's minimum");
    for (const unmet of [
      "a studio with a parent",
      "a tag with a parent",
      '3 or more tags whose names contain "a"',
      "a group with scenes",
      "a gallery with 2 or more images",
      "a clip",
      "a FEMALE and a MALE performer",
      "performers with and without a birthdate",
    ]) {
      expect(message).toContain(`- ${unmet}`);
    }
    // What the extension does provide is not listed
    expect(message).not.toContain("30 or more scenes");
    expect(message).not.toContain("a rated scene");
    expect(() => readFileSync(path.join(outDir, "library.json"))).toThrow(
      "ENOENT"
    );
  });

  it("writes library.json and manifest.ts whose FIXTURE_LIBRARY matches the entity counts", async () => {
    const shapePath = writeShape(testStashShape());
    const outDir = path.join(dir, "fixture");

    expect(generate({ shapePath, outDir, check: false })).toEqual([
      path.join(outDir, "library.json"),
      path.join(outDir, "manifest.ts"),
    ]);

    const library = parseReplayLibrary(
      JSON.parse(readFileSync(path.join(outDir, "library.json"), "utf8")),
      "library.json"
    );
    const manifestText = readFileSync(path.join(outDir, "manifest.ts"), "utf8");
    expect(manifestText.split("\n")[0]).toBe(
      "// Generated by npm run fixtures:generate; do not edit"
    );
    expect(manifestText).not.toMatch(/^import /m);

    const manifest: unknown = await import(
      pathToFileURL(path.join(outDir, "manifest.ts")).href
    );
    if (!isRecord(manifest)) throw new Error("manifest is not a module");
    expect(manifest.FIXTURE_API_KEY).toBe("stash-replay-key");
    expect(manifest.FIXTURE_ID_OFFSET).toBe(100000);
    expect(manifest.TEST_ENTITIES).toEqual(OWNER_TEST_ENTITIES);
    expect(manifest.FIXTURE_LIBRARY).toEqual({
      scenes: 36,
      performers: 11,
      studios: 10,
      tags: 11,
      groups: 3,
      galleries: 2,
      images: 9,
      clips: 2,
    });
    const keys = [
      "scenes",
      "performers",
      "studios",
      "tags",
      "groups",
      "galleries",
      "images",
      "clips",
    ];
    const counts = must(manifest.FIXTURE_LIBRARY);
    ENTITY_TYPES.forEach((type, index) => {
      expect(
        isRecord(counts) ? counts[must(keys[index])] : undefined,
        type
      ).toBe(library.entities[type].length);
    });

    // A second run finds nothing to change
    expect(generate({ shapePath, outDir, check: false })).toEqual([]);
  });

  it("--check exits 1 when a file would change", () => {
    const shapePath = writeShape(testStashShape());
    const outDir = path.join(dir, "fixture");
    const lines: string[] = [];
    const log = (line: string) => {
      lines.push(line);
    };

    // Nothing written yet: both files would change, and none is written
    expect(main(["--check"], { shapePath, outDir }, log)).toBe(1);
    expect(lines.join("\n")).toContain("library.json");
    expect(() => readFileSync(path.join(outDir, "manifest.ts"))).toThrow(
      "ENOENT"
    );
    expect(generate({ shapePath, outDir, check: true })).toEqual([
      path.join(outDir, "library.json"),
      path.join(outDir, "manifest.ts"),
    ]);

    expect(main([], { shapePath, outDir }, log)).toBe(0);
    expect(main(["--check"], { shapePath, outDir }, log)).toBe(0);

    // A hand edit is drift, and --check leaves it in place
    const libraryPath = path.join(outDir, "library.json");
    writeFileSync(libraryPath, "{}\n");
    expect(main(["--check"], { shapePath, outDir }, log)).toBe(1);
    expect(readFileSync(libraryPath, "utf8")).toBe("{}\n");
    expect(main(["--unknown"], { shapePath, outDir }, log)).toBe(2);
  });
});
